name: test

on: [push, pull_request]

permissions:
  contents: read

jobs:
  lint:
    name: RuboCop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: true
          rubygems: latest

      - name: Run RuboCop
        run: bundle exec rubocop

  test:
    strategy:
      matrix:
        entry:
          - { ruby: '3.0', grape: '1.8.0' }
          - { ruby: '3.1', grape: '1.8.0' }
          - { ruby: '3.2', grape: '1.8.0' }
          - { ruby: '3.3', grape: '1.8.0' }
          - { ruby: '3.4', grape: '1.8.0' }
          - { ruby: 'head', grape: '1.8.0' }
          - { ruby: '3.0', grape: '2.0.0' }
          - { ruby: '3.1', grape: '2.0.0' }
          - { ruby: '3.2', grape: '2.0.0' }
          - { ruby: '3.3', grape: '2.0.0' }
          - { ruby: '3.4', grape: '2.0.0' }
          - { ruby: 'head', grape: '2.0.0' }
          - { ruby: '3.0', grape: '2.1.3' }
          - { ruby: '3.1', grape: '2.1.3' }
          - { ruby: '3.2', grape: '2.1.3' }
          - { ruby: '3.3', grape: '2.1.3' }
          - { ruby: '3.4', grape: '2.1.3' }
          - { ruby: 'head', grape: '2.1.3' }
          - { ruby: '3.1', grape: '2.2.0' }
          - { ruby: '3.2', grape: '2.2.0' }
          - { ruby: '3.3', grape: '2.2.0' }
          - { ruby: '3.4', grape: '2.2.0' }
          - { ruby: 'head', grape: '2.2.0' }
          - { ruby: 'head', grape: 'HEAD' }
    name: test (ruby=${{ matrix.entry.ruby }}, grape=${{ matrix.entry.grape }})
    runs-on: ubuntu-latest
    env:
      GRAPE_VERSION: ${{ matrix.entry.grape }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.entry.ruby }}
        bundler-cache: true
    - name: Run tests
      run: bundle exec rake spec
